/*
 * This file is generated by jOOQ.
 */
package me.jko.jooq;


import javax.annotation.Generated;

import me.jko.jooq.tables.Comments;
import me.jko.jooq.tables.Posts;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.COMMENTS</code>.
     */
    public static final Comments COMMENTS = me.jko.jooq.tables.Comments.COMMENTS;

    /**
     * The table <code>PUBLIC.POSTS</code>.
     */
    public static final Posts POSTS = me.jko.jooq.tables.Posts.POSTS;
}
